name: Grafana Metrics
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  metrics:
    runs-on: ubuntu-24.04
    # Skip on PR if it's from a fork for security
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify metrics file
        run: |
          if [ ! -f metrics.json ]; then
            echo "Error: metrics.json file not found"
            exit 1
          fi
          
      - name: Send metrics
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
          GRAFANA_API_URL: https://api.grafana.com/metrics/v1/push
        run: |
          response=$(curl -w "\n%{http_code}" -X POST \
            -H "Authorization: Bearer $GRAFANA_API_KEY" \
            -H "Content-Type: application/json" \
            $GRAFANA_API_URL \
            -d @metrics.json)
          
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response body: $body"
          echo "Status code: $status_code"
          
          if [ "$status_code" -ge 400 ]; then
            echo "Error: Failed to send metrics to Grafana"
            exit 1
          fi